# Generated by Django 5.2 on 2025-04-23 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('connection_sent', 'Connection Sent'), ('connected', 'Connected')], default='connection_sent', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
