# Generated by Django 5.2 on 2025-04-23 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0002_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('linkedin_email', models.EmailField(blank=True, max_length=254)),
                ('outreach_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('info_shared', 'Info Shared'), ('F1', 'Follow Up 1'), ('F2', 'Follow Up 2'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], default='connected', max_length=20)),
                ('date_connected', models.DateTimeField(auto_now_add=True)),
                ('profile_pdf', models.FileField(blank=True, null=True, upload_to='profile_pdfs/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColdLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cold', models.DateTimeField(auto_now_add=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lead_management.connection')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lead_management.connection')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('free', 'Free Member'), ('paid', 'Paid Member')], max_length=10)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('biography_url', models.URLField()),
                ('featured_date', models.DateField()),
                ('assigned_editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_members', to=settings.AUTH_USER_MODEL)),
                ('community_builder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_members', to=settings.AUTH_USER_MODEL)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lead_management.connection')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('connection_sent', 'Connection Sent')], default='connection_sent', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='outreach_lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lead_management.outreachlead'),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
