# Generated by Django 5.2 on 2025-04-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0003_connection_coldlead_connectioncomment_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chat_screenshots/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='chat_screenshots',
            field=models.ManyToManyField(blank=True, related_name='connections', to='lead_management.chatscreenshot'),
        ),
    ]
