# Generated by Django 5.2 on 2025-04-24 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0004_chatscreenshot_connection_chat_screenshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectioncomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='lead_management.connectioncomment'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('info_shared', 'Info Shared'), ('F1', 'Follow Up 1'), ('F2', 'Follow Up 2'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('cold_lead', 'Cold Lead')], default='connected', max_length=20),
        ),
    ]
