# Generated by Django 5.2 on 2025-04-24 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0005_connectioncomment_parent_alter_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='project_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'project_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_builders', to=settings.AUTH_USER_MODEL),
        ),
    ]
