# Generated by Django 5.2 on 2025-04-29 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0006_userprofile_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='assigned_editor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'editor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_assigned_connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
