# Generated by Django 5.2 on 2025-05-02 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive_biographer', '0001_initial'),
        ('lead_management', '0007_connection_assigned_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='biographydraft',
            name='input_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biographydraft',
            name='is_finetune_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biographydraft',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biographydraft',
            name='output_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biographydraft',
            name='total_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biographydraft',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='FineTuningSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data_json', models.JSONField()),
                ('final_output', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_management.connection')),
            ],
        ),
    ]
